### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by yyewolf** [yyewolf/goaoc#1]
Small todo (may be missing things) :

- [x] Have a place for badges on the Readme template
- [x] Put the stars table on the Readme template
- [x] #3
- [x] Ask the user if they want to enable benchmarks
- [x] Add a CLI command to generate the readme
- [x] Add a CLI command to setup current day
- [x] Add a CLI command to benchmark current day (do not replace existing tests if they exist)
- [x] Add utility to get DefaultYear (WD before config before current)
- [x] Add utility to get DefaultDay (WD before current)
- [x] Setup : ask to add workflow (for stars)
